fix ReadTheDocs configuration
spacetelescope/stsci.skypac pull request #72
Opened 2024-05-17 18:23 UTC by zacharyburnett

closes #71

2024-05-17 18:32 UTC, pllim commented
Looks like `docs/source/conf.py` and possibly other related doc infrastructure also need updating.

2024-05-17 19:11 UTC, pllim commented
Something still isn't right. Somehow it ended up trying to build with a very old Sphinx v1.8.5 even though it initially found modern Sphinx v7

2024-05-17 19:13 UTC, pllim commented
Is this really necessary?

https://github.com/spacetelescope/stsci.skypac/blob/3a8d671fd2c25677fbb9014af2082399e53fb3fa/docs/source/conf.py#L207

2024-05-20 13:22 UTC, pllim commented
I think it finally installed and trying to build the docs but has problem finding the namespace packages.

```
* ModuleNotFoundError: No module named 'stsci.tools'
* AttributeError: module 'stsci' has no attribute 'skypac'
```

2024-05-20 13:37 UTC, zacharyburnett commented
ugh, another namespace issue. I'll take a look at this today

2024-05-20 13:42 UTC, pllim commented
Thanks!

2024-05-20 13:49 UTC, zacharyburnett commented
this is so odd 
```shell
❯ python -c "import stsci.tools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'stsci.tools'
```

2024-05-20 17:00 UTC, pllim commented
Looks like RTD had not built successfully for 2 years for this package. Probably have to clean up a bunch of tech debt first.

2024-05-20 17:32 UTC, pllim commented
So looking at one of the warnings:

```
WARNING: Failed to import stsci.skypac.parseat.
Possible hints:
* ModuleNotFoundError: No module named 'stsci.tools'
* AttributeError: module 'stsci' has no attribute 'skypac'
```

And the actual content of `docs/source/parseat.rst`:

```rst
===========================================================
Utility functions for parsing user catalog files for skypac
===========================================================

.. moduleauthor:: Mihai Cara <help@stsci.edu>

.. currentmodule:: stsci.skypac.parseat

.. automodule:: stsci.skypac.parseat
   :members:
```

I feel like possible hints might be red herring. My hunch is you have to tweak either currentmodule, automodule, or both. At this point, try to build the doc locally with different tweaks until this warning goes away, and then apply similar patches to the other API docs.

p.s. moduleauthor is unnecessary and probably can be removed.

2025-03-22 04:24 UTC, mcara approved these changes
Could you please rebase this?

2025-03-22 04:25 UTC, mcara requested changes
Could you please rebase this?

2025-08-12 00:01 UTC, merged